version: '3.9'

services:
  app:
    container_name: app_converter
    build:
      context: .
      dockerfile: converter/Dockerfile
    volumes:
      - ./converter:/home/appuser
      - temp_data:/tmp/
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres
      - pdf2html
    ports:
      - "3000:3000"
    env_file:
      - ./.env

  tg_bot:
    container_name: tg_bot_converter
    build:
      context: .
      dockerfile: tg_bot/Dockerfile
    volumes:
      - ./tg_bot:/home/appuser
    depends_on:
      - postgres
      - pdf2html
      - redis
      - app
    env_file:
      - ./.env

  pdf2html:
    container_name: pdf2html
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - temp_data:/tmp/

  postgres:
    image: postgres:latest
    container_name: postgres_converter
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - "5465:5432"
    volumes:
      - postgres_data_converter:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local
  postgres_data_converter:
  temp_data:
