"""init

Revision ID: 380f1679f45e
Revises: 
Create Date: 2025-02-11 22:00:58.509058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380f1679f45e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('tg_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id'),
    sa.UniqueConstraint('username', 'tg_id', name='users_unique_key')
    )
    op.create_table('formats_cross',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('format_from_id', sa.Integer(), nullable=False),
    sa.Column('format_to_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['format_from_id'], ['formats.id'], ),
    sa.ForeignKeyConstraint(['format_to_id'], ['formats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('format_from_id', 'format_to_id', name='formats_cross_unique_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('formats_cross')
    op.drop_table('users')
    op.drop_table('formats')
    # ### end Alembic commands ###
