"""add_types

Revision ID: 716c15572ab8
Revises: 890aeadf2854
Create Date: 2025-02-18 10:07:50.377650

"""
from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision = '716c15572ab8'
down_revision = '890aeadf2854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='actiontype',
        new_values=['START', 'CHOOSE_FROM', 'CHOOSE_TO', 'UPLOADING', 'GOT_RESULT', 'CONVERT', 'FEEDBACK'],
        affected_columns=[TableReference(table_schema='public', table_name='user_actions', column_name='action_type', existing_server_default="'START'::actiontype")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='actiontype',
        new_values=['START', 'CHOOSE_FROM', 'CHOOSE_TO', 'UPLOADING', 'GOT_RESULT'],
        affected_columns=[TableReference(table_schema='public', table_name='user_actions', column_name='action_type', existing_server_default="'START'::actiontype")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
