"""add_user_actions

Revision ID: bbef2112f46d
Revises: 380f1679f45e
Create Date: 2025-02-17 15:15:21.862157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbef2112f46d'
down_revision = '380f1679f45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('START', 'CHOOSE_FROM', 'CHOOSE_TO', 'UPLOADING', 'GOT_RESULT', name='actiontype').create(op.get_bind())
    op.create_table('user_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', postgresql.ENUM('START', 'CHOOSE_FROM', 'CHOOSE_TO', 'UPLOADING', 'GOT_RESULT', name='actiontype', create_type=False), server_default='START', nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_actions')
    sa.Enum('START', 'CHOOSE_FROM', 'CHOOSE_TO', 'UPLOADING', 'GOT_RESULT', name='actiontype').drop(op.get_bind())
    # ### end Alembic commands ###
